CREATE TABLE JOUEUR(
    idJoueur INTEGER PRIMARY KEY AUTOINCREMENT,
    pseudo TEXT UNIQUE NOT NULL
);

CREATE TABLE DIFFICULTE(
    idDifficulte INTEGER PRIMARY KEY AUTOINCREMENT,
    nomDifficulte TEXT UNIQUE NOT NULL,
    rangeMin INTEGER NOT NULL,
    rangeMax INTEGER NOT NULL,
    nbVirgules BOOLEAN NOT NULL
);

CREATE TABLE SCORE(
    idScore INTEGER PRIMARY KEY AUTOINCREMENT,
    essai INTEGER NOT NULL,
    idJoueur INTEGER NOT NULL,
    idDifficulte INTEGER NOT NULL,
    FOREIGN KEY (idJoueur) REFERENCES JOUEUR(idJoueur),
    FOREIGN KEY (idDifficulte) REFERENCES DIFFICULTE(idDifficulte)
);

